coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 1%
        base: auto
        paths:
          - "src"
        # advanced
        #branches:
        #  - master
        #if_not_found: success
        #if_ci_failed: error
        #informational: False
        #only_pulls: false
